# Generated by Django 5.0.6 on 2024-10-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_discounted_price_cart_image_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.URLField(),
        ),
    ]
